-- ============================================================
-- Seed del catálogo de clientes (generado 07/07/2026)
-- Fuente: agrupación de los 501 strings distintos de shipments.cliente
-- por clave normalizada (normalizeClienteKey de src/lib/clientCatalog.ts)
-- + fusiones de typos evidentes. 359 clientes canónicos.
--
-- NO ejecutar sin revisar. Idempotente:
--  · ON CONFLICT (id) DO NOTHING
--  · No inserta si ya existe un cliente con el mismo nombre (case-insensitive)
--    → los 3 clients de prueba existentes (BRIAN / Tincho / Daiana) no se tocan.
-- Los campos legales (razón social, CUIT, país, dirección) quedan NULL para
-- completar a mano. cliente_pattern queda '' → el login del portal deriva el
-- patrón de name+aliases.
-- Excluidos (genéricos sin forma societaria, ≤2 cargas): AUTO, VARIOS, TONY,
-- MULTIPLES SHIPPERS, y los 15 registros con cliente vacío.
-- ============================================================

insert into clients (id, email, name, company, cliente_pattern, aliases)
select v.id, '', v.name, '', '', nullif(v.aliases, '')
from (values
  ('cl-3d-parts', '3D PARTS', ''),
  ('cl-5-oceanos', '5 OCEANOS S.A', ''),
  ('cl-abratte-juan-agustin', 'ABRATTE JUAN AGUSTIN', ''),
  ('cl-accord-group', 'ACCORD GROUP S.R.L', 'ACORD GROUP S.R.L'),
  ('cl-aconcagua-distillery', 'ACONCAGUA DISTILLERY SA', ''),
  ('cl-acuerdos', 'ACUERDOS S.R.L', ''),
  ('cl-adas', 'ADAS S.R.L.', ''),
  ('cl-adolfo-borda', 'ADOLFO BORDA', ''),
  ('cl-agro-andina', 'AGRO ANDINA S.A', ''),
  ('cl-agro-industria', 'AGRO INDUSTRIA', ''),
  ('cl-agrocentro', 'AGROCENTRO', ''),
  ('cl-agustin-bacigalupe', 'AGUSTIN BACIGALUPE', ''),
  ('cl-ait', 'AIT S.A', 'AIT S.A., AIT SA'),
  ('cl-alejandro-siri', 'ALEJANDRO SIRI', ''),
  ('cl-alfa-arg', 'ALFA ARG S.A', ''),
  ('cl-alfa-argentina', 'ALFA ARGENTINA S.A', 'ALFA ARGENTINA, ALFA ARGENTINA S.A.'),
  ('cl-alfredo-pinto', 'ALFREDO PINTO', ''),
  ('cl-alimentaria', 'ALIMENTARIA S.R.L', ''),
  ('cl-alimentaria-monte-cristo', 'ALIMENTARIA MONTE CRISTO S.R.L.', ''),
  ('cl-alj-brasil', 'ALJ BRASIL', ''),
  ('cl-almaq', 'ALMAQ S.R.L.', ''),
  ('cl-amismet', 'AMISMET SA', ''),
  ('cl-andretich', 'ANDRETICH SA', 'ANDRETICH'),
  ('cl-antunes-ferreira-tatiana-soledad', 'ANTUNES FERREIRA TATIANA SOLEDAD', ''),
  ('cl-aran-tecnologias', 'ARAN TECNOLOGIAS', ''),
  ('cl-arcafe', 'ARCAFE', ''),
  ('cl-arcafe-entrega-en-planta', 'ARCAFE- entrega en planta', ''),
  ('cl-aro-plastyc', 'ARO PLASTYC S.A.S', 'ARO PLASTYC S.A.S.'),
  ('cl-aryes', 'ARYES LTDA', ''),
  ('cl-austro', 'AUSTRO S.A.', ''),
  ('cl-automach', 'AUTOMACH S.R.L.', ''),
  ('cl-automatiza', 'AUTOMATIZA S.A', 'AUTOMATIZA S.A.'),
  ('cl-av-industrias', 'AV INDUSTRIAS S.R.L.', ''),
  ('cl-avenires', 'AVENIRES', ''),
  ('cl-bacigalupe', 'BACIGALUPE', ''),
  ('cl-balsamo', 'BALSAMO S.A', 'BALSAMO, BALSAMO S.A., BALSAMO SA'),
  ('cl-bantiger', 'BANTIGER S.A.S', ''),
  ('cl-barriaz', 'BARRIAZ S.A.', ''),
  ('cl-basso', 'BASSO', 'BASSO S.A.'),
  ('cl-bbm-solutions', 'BBM SOLUTIONS S.R.L.', 'BBM SOLUTIONS S.R.L'),
  ('cl-benites', 'BENITES', ''),
  ('cl-benites-leandro', 'BENITES LEANDRO', ''),
  ('cl-benites-leandro-emmanuel', 'BENITES LEANDRO EMMANUEL', ''),
  ('cl-benitez', 'BENITEZ S.R.L', ''),
  ('cl-bici-peretti', 'BICI PERETTI S.A.', ''),
  ('cl-bicicletas-tomaselli', 'BICICLETAS TOMASELLI S.A.', 'BICILETAS TOMASELLI S.A.'),
  ('cl-bike-group', 'BIKE GROUP SA', ''),
  ('cl-bkstm', 'BKSTM SAS', 'BKSTM'),
  ('cl-bonetto', 'BONETTO', ''),
  ('cl-border-argentina', 'BORDER ARGENTINA SA', ''),
  ('cl-bpb', 'BPB', ''),
  ('cl-bpb-mediterranea', 'BPB MEDITERRANEA S.A.', 'BPB MEDITERRANEA S.A'),
  ('cl-campinox', 'CAMPINOX', ''),
  ('cl-cap-e-hijos', 'CAP E HIJOS', ''),
  ('cl-carina-andrea-marchionatti', 'CARINA ANDREA MARCHIONATTI', ''),
  ('cl-carlos-andretich', 'CARLOS ANDRETICH S.A', 'CARLOS ANDRETICH S.A.'),
  ('cl-carreteles-rafaela', 'CARRETELES RAFAELA SA', 'CARRETELES RAFAELA S.A'),
  ('cl-castro-cristian-martin', 'CASTRO CRISTIAN MARTIN', ''),
  ('cl-catador', 'CATADOR S.R.L', ''),
  ('cl-ceba-lucas-marcos', 'CEBA LUCAS MARCOS', ''),
  ('cl-cebemar-diesel', 'CEBEMAR DIESEL', ''),
  ('cl-cedicor', 'CEDICOR', 'CEDICOR S.R.L, CEDICOR S.R.L.'),
  ('cl-cemedin', 'CEMEDIN SRL', ''),
  ('cl-cena-hnos', 'CENA HNOS SRL', 'CENA HNOS'),
  ('cl-cena-lucas-marcos', 'CENA LUCAS MARCOS', ''),
  ('cl-ceneri', 'CENERI', ''),
  ('cl-centro-sbz', 'CENTRO SBZ S.A', 'CENTRO SBZ'),
  ('cl-cerezuela', 'CEREZUELA', ''),
  ('cl-chiapero-y-asoc', 'CHIAPERO Y ASOC. S.R.L.', ''),
  ('cl-cima', 'CIMA S.R.L.', ''),
  ('cl-ciuffo', 'CIUFFO', ''),
  ('cl-colsecor-coop', 'COLSECOR COOP. LTDA.', ''),
  ('cl-conax', 'CONAX SA', 'CONAX, CONAX S.A'),
  ('cl-conosur-invest', 'CONOSUR INVEST S.A.', ''),
  ('cl-control-uno', 'CONTROL UNO S.A', ''),
  ('cl-coop-electrica-y-de-obras-y-serv-publicos', 'COOP ELECTRICA Y DE OBRAS Y SERV PUBLICOS', ''),
  ('cl-cooperativa-electrica', 'COOPERATIVA ELECTRICA', ''),
  ('cl-costamagna', 'COSTAMAGNA', ''),
  ('cl-costamagna-carlos', 'COSTAMAGNA CARLOS', 'COSTAMAGNA CARLOS S.A, COSTAMAGNA CARLOS S.A.'),
  ('cl-costamagna-carlos-alberto', 'COSTAMAGNA CARLOS ALBERTO', ''),
  ('cl-cotahua', 'COTAHUA S.A.', ''),
  ('cl-cpa-producciones', 'CPA PRODUCCIONES S.R.L.', 'CPA PRODUCCIONES'),
  ('cl-cristian-acrich', 'CRISTIAN ACRICH SAS', ''),
  ('cl-crontab', 'CRONTAB SA', ''),
  ('cl-ct-proyectos', 'CT PROYECTOS S.R.L', ''),
  ('cl-cultivar', 'CULTIVAR S.R.L.', 'Cultivar SRL'),
  ('cl-custom-agent', 'CUSTOM AGENT S.A.S.', 'CUSTOM AGENT SAS'),
  ('cl-dabar-y-cia', 'DABAR & CIA S.R.L.', 'DABAR & CIA S.R.L, DABAR Y CIA S.R.L, DABAR Y CIA S.R.L., DABAR Y CIA SRL'),
  ('cl-dafese', 'DAFESE S.R.L.', 'DAFESE S.R.L'),
  ('cl-daitec', 'DAITEC S.A.S.', ''),
  ('cl-dante-melano', 'DANTE MELANO', ''),
  ('cl-dario-a-delfabro', 'DARIO A. DELFABRO', ''),
  ('cl-dario-gonella', 'DARIO GONELLA', ''),
  ('cl-dayco-argentina', 'DAYCO ARGENTINA SA', 'DAYCO ARGENTINA'),
  ('cl-defese', 'DEFESE SRL', 'DEFESE S.R.L'),
  ('cl-delfabro', 'DELFABRO', 'DEL FABRO S.R.L, DEL FABRO S.R.L., DELFABRO SRL'),
  ('cl-denimed', 'DENIMED S.A.', ''),
  ('cl-dent-3d', 'DENT 3D', 'DENT 3D S.A.S, DENT 3D S.A.S.'),
  ('cl-dent3d', 'DENT3D S.R.L', 'DENT3D SAS, DENT3D SRL'),
  ('cl-deposito-de-piedras-color', 'DEPOSITO DE PIEDRAS COLOR S.R.L', ''),
  ('cl-deposito-piedras-color', 'DEPOSITO PIEDRAS COLOR SRL', ''),
  ('cl-desert-capital', 'DESERT CAPITAL SAS', ''),
  ('cl-di-benetto', 'DI BENETTO', ''),
  ('cl-di-tomaso', 'DI TOMASO S.R.L.', 'DI TOMASO S.R.L'),
  ('cl-distribuidora-vilte', 'DISTRIBUIDORA VILTE SRL', ''),
  ('cl-dom-distribuciones', 'D.O.M. DISTRIBUCIONES S.A.', 'D.O.M. DISTRIBUCIONES, DOM DISTRUBUCIONES SA'),
  ('cl-dualcasing', 'DUALCASING S.R.L', ''),
  ('cl-ecowin', 'ECOWIN S.A', ''),
  ('cl-el-panta', 'EL PANTA S.A.', 'EL PANTA S.A'),
  ('cl-elda', 'ELDA S.R.L', 'ELDA S.R.L.'),
  ('cl-electro-cordoba', 'ELECTRO CORDOBA S.A', 'ELECTRO CORDOBA SA'),
  ('cl-elorza-agro', 'ELORZA AGRO S.R.L', 'ELORZA AGRO SRL'),
  ('cl-emazzi', 'EMAZZI S.R.L.', ''),
  ('cl-emintex', 'EMINTEX S.A', ''),
  ('cl-energia-segura', 'ENERGIA SEGURA S.A.', ''),
  ('cl-enki-contructora', 'ENKI CONTRUCTORA S.A.S', ''),
  ('cl-envases-caraes', 'ENVASES CARAES S.A.', 'EVACES CARAES S.A'),
  ('cl-espa', 'ESPA S.A', 'ESPA S.A.'),
  ('cl-estructuras-androetto', 'ESTRUCTURAS ANDROETTO', ''),
  ('cl-eyito', 'EYITO SA', ''),
  ('cl-fabricio-nicolas-libra-puglie', 'FABRICIO NICOLAS LIBRA PUGLIE', ''),
  ('cl-falco-walter', 'FALCO WALTER', ''),
  ('cl-fass-evolucion', 'FASS EVOLUCIÓN S.A.S.', ''),
  ('cl-feet', 'FEET S.A.', ''),
  ('cl-ferreyra-diego-jeremias', 'FERREYRA DIEGO JEREMIAS', ''),
  ('cl-fh-automatizaciones', 'FH AUTOMATIZACIONES', ''),
  ('cl-fiber-home', 'FIBER HOME', ''),
  ('cl-fitness-emporium', 'FITNESS EMPORIUM', ''),
  ('cl-flat-rack-metal-noet', 'FLAT RACK METAL NOET', ''),
  ('cl-fraga', 'FRAGA S.R.L', ''),
  ('cl-francisco-nicolas-spano', 'FRANCISCO NICOLAS SPANO', ''),
  ('cl-freiberg', 'FREIBERG', ''),
  ('cl-frio-raf', 'FRIO RAF', 'FRIO RAF S.A, FRIO RAF S.A.'),
  ('cl-frontera-living', 'FRONTERA LIVING SA', 'FRONTERA LIVING, FRONTERA LIVING S.A, FRONTERA LIVING S.A.'),
  ('cl-frund', 'FRUND', ''),
  ('cl-fumiscor', 'FUMISCOR S.A.', ''),
  ('cl-fumiscor-famma', 'FUMISCOR / FAMMA', ''),
  ('cl-funcionales', 'FUNCIONALES S.A', ''),
  ('cl-galander', 'GALANDER S.A.', ''),
  ('cl-galvanizados-cordoba', 'GALVANIZADOS CORDOBA SRL', ''),
  ('cl-garcia-gustavo-sebastian', 'GARCIA GUSTAVO SEBASTIAN', ''),
  ('cl-giacomelli', 'GIACOMELLI S.A', ''),
  ('cl-gieco', 'GIECO S.A', ''),
  ('cl-global-chain', 'GLOBAL CHAIN S.A.S', ''),
  ('cl-global-visum', 'GLOBAL VISUM S.A.', ''),
  ('cl-gonzalo-cementados', 'GONZALO CEMENTADOS', ''),
  ('cl-good-rest', 'GOOD REST S.R.L.', 'GOOD RESRT S.R.L.'),
  ('cl-grana', 'GRANA SA', 'GRANA S.R.L.'),
  ('cl-granados-del-centro', 'GRANADOS DEL CENTRO', 'GANADOS DEL CENTRO'),
  ('cl-grobear', 'GROBEAR S.A.S.', ''),
  ('cl-gropius', 'GROPIUS S.A.S.', ''),
  ('cl-grupo-coba-energia', 'GRUPO COBA ENERGIA S.A.S.', ''),
  ('cl-grupo-dos', 'GRUPO DOS S.A.S', ''),
  ('cl-grupo-vindur', 'GRUPO VINDUR S.A.', ''),
  ('cl-gs-technology', 'GS TECHNOLOGY S.R.L', ''),
  ('cl-guantex', 'GUANTEX SRL', ''),
  ('cl-guareschi-valeria-soledad', 'GUARESCHI VALERIA SOLEDAD', ''),
  ('cl-guidi-ivo-daniel', 'GUIDI IVO DANIEL', ''),
  ('cl-hardcore', 'HARDCORE', ''),
  ('cl-hardcore-fitness', 'HARDCORE FITNESS SRL', 'HARDCORE FIRNESS SRL, HARDCORE FITNESS S.R.L, HARDCORE FITNESS S.R.L., HARDOCE FITNESS S.R.L, HARDORE FITNESS S.R.L'),
  ('cl-hdt-asia-latam', 'HDT ASIA LATAM', ''),
  ('cl-heber-hegi', 'HEBER HEGI', ''),
  ('cl-helir', 'HELIR S.A.', ''),
  ('cl-helisa', 'HELISA SRL', ''),
  ('cl-helit', 'HELIT S.A.', ''),
  ('cl-hidradc', 'HIDRADC S.A.S.', ''),
  ('cl-hidraulica-dc', 'HIDRAULICA DC S.R.L.', 'HIDRAULICA DC'),
  ('cl-hidraulica-san-franc', 'HIDRAULICA SAN FRANC.', ''),
  ('cl-hidraulica-san-francisco', 'HIDRÁULICA SAN FRANCISCO', 'HIDRÁULICA SAN FRANCISCO SRL'),
  ('cl-hidrobull', 'HIDROBULL', ''),
  ('cl-hipec', 'HIPEC S.R.L.', ''),
  ('cl-hiqual', 'HIQUAL S.R.L.', ''),
  ('cl-hj-herrera', 'HJ HERRERA S.R.L.', ''),
  ('cl-inchik', 'INCHIK S.A', ''),
  ('cl-industrial-plasticas-bernal', 'INDUSTRIAL PLASTICAS BERNAL S.A.I.C', ''),
  ('cl-industrias-jed', 'INDUSTRIAS JED S.R.L.', 'INDUSTRIAS JED SR.L., INDUSTRIAS JED SRL'),
  ('cl-industrias-torreggiani', 'INDUSTRIAS TORREGGIANI', ''),
  ('cl-inelpa', 'INELPA', 'INELPA S.A, INELPA S.A.'),
  ('cl-inelpa-transf', 'INELPA TRANSF. S.A.', ''),
  ('cl-inelpa-transformadores', 'INELPA TRANSFORMADORES', 'INELPA TRANFORMADORES, INELPA TRANFORMADORES SA, INELPA TRANSFORMADORES SA'),
  ('cl-insumos-log', 'INSUMOS LOG', ''),
  ('cl-intento-inflexible', 'INTENTO INFLEXIBLE S.A.S', ''),
  ('cl-interglobal-trade', 'INTERGLOBAL TRADE', ''),
  ('cl-iommi', 'IOMMI', ''),
  ('cl-ir-argentina', 'IR ARGENTINA S.R.L', 'IR ARGENTINA S.R.L., IR ARGENTINA SRL'),
  ('cl-ivo-daniel-guidi', 'IVO DANIEL GUIDI', ''),
  ('cl-jmv', 'JMV S.R.L', 'JMV S.R.L., JMV SRL, JVM S.R.L'),
  ('cl-jorge-alberto-allocco', 'JORGE ALBERTO ALLOCCO', ''),
  ('cl-juan-fernando-rosa', 'JUAN FERNANDO ROSA', ''),
  ('cl-juan-quintero', 'JUAN QUINTERO', ''),
  ('cl-kamiro', 'KAMIRO', ''),
  ('cl-la-industrial-salinera', 'LA INDUSTRIAL SALINERA SA', ''),
  ('cl-la-quimera', 'LA QUIMERA S.A', ''),
  ('cl-lambert', 'LAMBERT', ''),
  ('cl-lambert-atilio', 'LAMBERT ATILIO', ''),
  ('cl-lancioni', 'LANCIONI', 'LANCIONI SRL'),
  ('cl-ledlar', 'LEDLAR', ''),
  ('cl-leonardo-benites', 'LEONARDO BENITES', ''),
  ('cl-leonardo-emmanuel-benites', 'LEONARDO EMMANUEL BENITES', ''),
  ('cl-lisal', 'LISAL', ''),
  ('cl-map', 'MAP S.A.', ''),
  ('cl-marcos-emanuel-alfonso', 'MARCOS EMANUEL ALFONSO', ''),
  ('cl-mario-tomaselli', 'MARIO TOMASELLI', ''),
  ('cl-matias-jalil', 'MATIAS JALIL', ''),
  ('cl-maxion-mont', 'MAXION MONT', ''),
  ('cl-maxion-montich', 'MAXION MONTICH SA', ''),
  ('cl-mcrbike', 'MCRBIKE SA', ''),
  ('cl-mediterranea-diesel', 'MEDITERRÁNEA DIESEL SRL', ''),
  ('cl-metagro', 'METAGRO S.R.L', ''),
  ('cl-metal-noet', 'METAL NOET S.R.L.', 'METAL NOET'),
  ('cl-metal-pilar', 'METAL PILAR S.A', ''),
  ('cl-metal-veneta', 'METAL VENETA S.A.', ''),
  ('cl-metalurgica-bonano', 'METALURGICA BONANO', ''),
  ('cl-metalurgica-carlos-juarez', 'METALURGICA CARLOS JUAREZ SRL', ''),
  ('cl-metalurgica-el-abrojal', 'METALURGICA EL ABROJAL S.R.L', ''),
  ('cl-microscopy', 'MICROSCOPY S.A.', ''),
  ('cl-miguel-azana', 'MIGUEL AZANA', ''),
  ('cl-millex', 'MILLEX S.A', ''),
  ('cl-mitre-international-corporation', 'MITRE INTERNATIONAL CORPORATION', ''),
  ('cl-mojon-uno', 'MOJON UNO S.A', ''),
  ('cl-molco-sport', 'MOLCO SPORT S.R.L.', ''),
  ('cl-molfino', 'MOLFINO', ''),
  ('cl-molfino-hnos', 'MOLFINO HNOS S.A.', 'MOLFINO GNOS S.A, MOLFINO HNOS S.A, MOLFINO HNOS S.A.S.'),
  ('cl-morandini-fernando', 'MORANDINI FERNANDO', ''),
  ('cl-moroni-ricardo-rinaldo', 'MORONI RICARDO RINALDO', ''),
  ('cl-motors-parts', 'MOTORS PARTS', ''),
  ('cl-mueble-gacela', 'MUEBLE GACELA', ''),
  ('cl-muebles-gacela', 'MUEBLES GACELA', ''),
  ('cl-nabel', 'NABEL S.R.L.', ''),
  ('cl-nasr', 'NASR', ''),
  ('cl-nasr-jorge-luis', 'NASR JORGE LUIS', ''),
  ('cl-naxos-kut', 'NAXOS KUT S.A', ''),
  ('cl-nome-tires', 'NOME TIRES S.R.L.', 'NOME TIRES S.R.L, NOME TIRES SRL'),
  ('cl-novecientos-seis', 'NOVECIENTOS SEIS S.R.L', ''),
  ('cl-nuovamec', 'NUOVAMEC S.A', ''),
  ('cl-nutrifarms', 'NUTRIFARMS', ''),
  ('cl-oleohidraulica-gea', 'OLEOHIDRAULICA GEA S.R.L.', ''),
  ('cl-olga-cristina-tencaioli', 'OLGA CRISTINA TENCAIOLI', ''),
  ('cl-orientar', 'ORIENTAR S.A.S.', 'ORIENTAR S.A.S'),
  ('cl-oscar-massa', 'OSCAR MASSA', ''),
  ('cl-pablo-simes', 'PABLO SIMES', ''),
  ('cl-pantallas-y-displays', 'PANTALLAS Y DISPLAYS', ''),
  ('cl-papanicolau', 'PAPANICOLAU', ''),
  ('cl-pauny', 'PAUNY SA', 'PAUNY S.A.'),
  ('cl-pc-producciones', 'PC PRODUCCIONES', ''),
  ('cl-pcs-argentina', 'PCS ARGENTINA', ''),
  ('cl-pegasus-bearing', 'PEGASUS BEARING SA', ''),
  ('cl-pellacani', 'PELLACANI S.R.L.', 'PELLACANI S.R.L, PELLACANI SRL, PELLSCANI SRL'),
  ('cl-peloffu-guido-agustin', 'PELOFFU GUIDO AGUSTÍN', ''),
  ('cl-peluffo', 'PELUFFO', ''),
  ('cl-peretti', 'PERETTI', ''),
  ('cl-pertrak', 'PERTRAK', 'PERTRACK, PERTRAK S.A, PERTRAK S.A.'),
  ('cl-piccoto', 'PICCOTO', ''),
  ('cl-pino-sub', 'PINO SUB', ''),
  ('cl-plasticos-rodrigues', 'PLASTICOS RODRIGUES', ''),
  ('cl-plumita', 'PLUMITA SRL', ''),
  ('cl-polifilm', 'POLIFILM S.A', 'POLIFILM'),
  ('cl-praga', 'PRAGA S.R.L.', ''),
  ('cl-precons', 'PRECONS S.R.L.', 'PRECONS, PRECONS S.R.L'),
  ('cl-pretensados-cordoba', 'PRETENSADOS CORDOBA S.R.L', ''),
  ('cl-procar', 'PROCAR S.R.L', 'PROCAR SRL'),
  ('cl-productos-funcionales', 'PRODUCTOS FUNCIONALES S.A.', ''),
  ('cl-proteccion-inteligente', 'PROTECCION INTELIGENTE S.A.', ''),
  ('cl-protectia', 'Protectia', ''),
  ('cl-pushkena', 'PUSHKENA', ''),
  ('cl-pushkena-textil', 'PUSHKENA TEXTIL S.A', 'PUSHKENA TEXTIL SA'),
  ('cl-quiroga', 'QUIROGA', ''),
  ('cl-rayces', 'RAYCES', ''),
  ('cl-rc-cuaser', 'RC CUASER SA', ''),
  ('cl-rdm', 'RDM', ''),
  ('cl-rdm-abea', 'RDM - ABEA S.A.', 'RDM - ABEA'),
  ('cl-rdm-aconcagua-distillery', 'RDM - ACONCAGUA DISTILLERY', ''),
  ('cl-rdm-akron-comercial', 'RDM - AKRON COMERCIAL S.A.', ''),
  ('cl-rdm-allocco-jorge-alberto', 'RDM - ALLOCCO JORGE ALBERTO', ''),
  ('cl-rdm-bertona-alfredo-jose', 'RDM - BERTONA ALFREDO JOSE', ''),
  ('cl-rdm-cebemar-diesel', 'RDM - CEBEMAR DIESEL', ''),
  ('cl-rdm-cena-hnos', 'RDM - CENA HNOS', 'RDM - CENA HNOS ARG'),
  ('cl-rdm-cena-lucas-marcos', 'RDM - CENA LUCAS MARCOS', ''),
  ('cl-rdm-cooperativa-electrica', 'RDM - COOPERATIVA ELECTRICA', ''),
  ('cl-rdm-famiglia-unita', 'RDM - FAMIGLIA UNITA', ''),
  ('cl-rdm-frontera-living', 'RDM - FRONTERA LIVING S.A.', 'RDM - FRONTERA LIVING'),
  ('cl-rdm-good-rest', 'RDM - GOOD REST S.R.L.', 'RDM - GOOD RESRT S.R.L.'),
  ('cl-rdm-helit', 'RDM - HELIT S.A.', ''),
  ('cl-rdm-industria-hidraulica-mercosur', 'RDM - INDUSTRIA HIDRAULICA MERCOSUR', ''),
  ('cl-rdm-kuarzo-diseno-y-const', 'RDM - KUARZO DISEÑO Y CONST.', ''),
  ('cl-rdm-marchionatti-carina', 'RDM - MARCHIONATTI CARINA', 'RDM - MARCHIONATTI'),
  ('cl-rdm-metagro', 'RDM - METAGRO S.R.L.', 'RDM - METAGRO S.R.L'),
  ('cl-rdm-metalurgica-bonano', 'RDM - METALURGICA BONANO S.A', ''),
  ('cl-rdm-perotti', 'RDM - PEROTTI', ''),
  ('cl-rdm-pilca', 'RDM - PILCA S.A', ''),
  ('cl-rdm-plumita', 'RDM - PLUMITA', ''),
  ('cl-rdm-remontar', 'RDM - REMONTAR S.R.L', ''),
  ('cl-rdm-ritma', 'RDM - RITMA S.R.L.', 'RDM - RITMA SRL'),
  ('cl-rdm-rodolfo-pagliaroli-e-hijos', 'RDM - RODOLFO PAGLIAROLI E HIJOS S.R.L.', ''),
  ('cl-rdm-sartoni-angel-alberto', 'RDM - SARTONI ANGEL ALBERTO', ''),
  ('cl-rdm-serena-engranajes', 'RDM SERENA ENGRANAJES', ''),
  ('cl-rdm-tool-shop', 'RDM - TOOL SHOP S.R.L.', ''),
  ('cl-rdm-v-y-t-exclusive', 'RDM - V Y T EXCLUSIVE S.R.L.', ''),
  ('cl-rdm-weg-equip-electricos', 'RDM - WEG EQUIP. ELECTRICOS S.A', ''),
  ('cl-rea-jet', 'REA JET S.R.L.', ''),
  ('cl-recmetal', 'RECMETAL SA', ''),
  ('cl-rhino-direct', 'RHINO DIRECT', ''),
  ('cl-ricambi-auto-sport', 'RICAMBI AUTO SPORT S.R.L', ''),
  ('cl-rinero-hermanos', 'RINERO HERMANOS S.R.L', 'RINERO HERMANOS SRL'),
  ('cl-rio-block', 'RIO BLOCK S.R.L', ''),
  ('cl-ritma', 'RITMA SRL', ''),
  ('cl-rodados-sport', 'RODADOS SPORT SRL', 'RODADDOS SPORT'),
  ('cl-rodolfo-pagliaroli', 'RODOLFO PAGLIAROLI', ''),
  ('cl-rodolfo-pagliaroli-e-hijos', 'RODOLFO PAGLIAROLI E HIJOS S.R.L.', 'RODOLFO PAGLIAROLI E HIJOS SRL'),
  ('cl-salvador-aires', 'SALVADOR AIRES', ''),
  ('cl-sch-comercial', 'SCH COMERCIAL S.A.S', 'SCH COMERCILAS S.A.S.'),
  ('cl-serena-engranajes', 'SERENA ENGRANAJES SRL', 'SERENA ENGRANAJES'),
  ('cl-sericentro', 'SERICENTRO', ''),
  ('cl-serra', 'SERRA S.R.L.', ''),
  ('cl-servicios', 'SERVICIOS S.R.L', ''),
  ('cl-servicios-industriales', 'SERVICIOS INDUSTRIALES SRL', ''),
  ('cl-siri-alejandro-esteban', 'SIRI ALEJANDRO ESTEBAN', ''),
  ('cl-siscadat', 'SISCADAT S.A.', ''),
  ('cl-sistemas-marinos', 'SISTEMAS MARINOS', ''),
  ('cl-smart-fit', 'SMART FIT', ''),
  ('cl-smartfit-paraguay', 'SMARTFIT PARAGUAY SA', ''),
  ('cl-smartfit-uruguay', 'SMARTFIT URUGUAY S.A', ''),
  ('cl-smartgas', 'SMARTGAS S.R.L', ''),
  ('cl-smartsupplier', 'SMARTSUPPLIER SA', ''),
  ('cl-soldar', 'SOLDAR S.R.L.', 'SOLDAAR, SOLDAR S.R L.'),
  ('cl-sportcom-uru', 'SPORTCOM URU S.A.S.', ''),
  ('cl-staal', 'STAAL S.A.S.', 'STAAL SAS'),
  ('cl-tacoma', 'TACOMA', ''),
  ('cl-tacoma-argentina', 'TACOMA ARGENTINA S.R.L', 'TACOMA ARGENTINA S.A., TACOMA ARGENTINA S.A, TACOMA ARGENTINA SA, TACOMA ARGETINA S.A.'),
  ('cl-tacural-industrial-y-servicios', 'TACURAL INDUSTRIAL Y SERVICIOS', ''),
  ('cl-tecmic', 'TECMIC S.R.L', 'TECMIC S.R.L., TECMIC SRL'),
  ('cl-tecno3', 'TECNO3', ''),
  ('cl-titantec', 'TITANTEC', ''),
  ('cl-todo-diesel', 'TODO DIESEL S.A.S', 'TODO DIESEL'),
  ('cl-tomaselli', 'TOMASELLI', ''),
  ('cl-tool-shop', 'TOOL SHOP SRL', 'TOOL SHOP, Tool Shop S.R.L.'),
  ('cl-tooling-corp', 'TOOLING CORP S.A', 'TOOLING CORP'),
  ('cl-tp', 'TP S.R.L.', 'TP, TP S.R.L, TP SRL'),
  ('cl-tp-srl-add', 'TP SRL ADD', ''),
  ('cl-tp-srl-add-rufino-cuervo', 'TP SRL ADD RUFINO CUERVO', ''),
  ('cl-tti-solutions', 'TTI SOLUTIONS S.A.S.', 'TTI SOLUTIONS, TTI SOLUTIONS SAS'),
  ('cl-v-y-t-exclusive', 'V y T Exclusive S.R.L', ''),
  ('cl-vanesa-grisel-martin', 'VANESA GRISEL MARTIN', ''),
  ('cl-vch-importadora-exportadora', 'VCH IMPORTADORA EXPORTADORA', ''),
  ('cl-veicolo', 'VEICOLO SRL', ''),
  ('cl-velsch-irrigation', 'VELSCH IRRIGATION S.A.S', ''),
  ('cl-vending', 'VENDING', ''),
  ('cl-venturi-hnos', 'VENTURI HNOS S.A', 'VENTURI HNOS S.A CIF, VENTURI HNOS. SA CIF'),
  ('cl-vescovo', 'VESCOVO', ''),
  ('cl-vidpia', 'VIDPIA', 'VIDPIA SAICF'),
  ('cl-vmg', 'VMG S.A.', 'VMG S.A'),
  ('cl-voip-experts', 'VOIP EXPERTS S.R.L.', ''),
  ('cl-vottero', 'VOTTERO', ''),
  ('cl-vulcano', 'VULCANO S.A', 'VULCANO, VULCANO S.A.'),
  ('cl-west-indian', 'WEST INDIAN', ''),
  ('cl-west-indian-coffee', 'WEST INDIAN COFFEE S.R.L.', ''),
  ('cl-yemen', 'YEMEN S.A', 'YEMEN, YEMEN SA'),
  ('cl-zb-argentina', 'ZB ARGENTINA S.R.L.', 'ZB ARGENTINA S.R.L'),
  ('cl-zig-argentina', 'ZIG ARGENTINA S.A.S.', '')
) as v(id, name, aliases)
where not exists (
  select 1 from clients c where lower(btrim(c.name)) = lower(btrim(v.name))
)
on conflict (id) do nothing;

-- Verificación sugerida:
-- select count(*) from clients;  -- esperado: ~359 + los preexistentes
